# Site settings
title : Sen's Blog
head_title : 张森的博客
description: 张森的博客，关于计算机、数学等相关技术爱好
tagline: 业精于勤而荒于嬉，行成于思而毁于随。
url:
author:
    name: Sen Zhang
    github: SenZhangAI
    email: szhang_hust@qq.com
    twitter:
    facebook:
    weibo:
    zhihu: http://www.zhihu.com/people/sen-zhang-73
    wiki: wiki
    stackoverflow: http://stackoverflow.com/users/4854570/senzhang
atom_path: /atom.xml
rss_path: /rss.xml
donate_url:

# Comment
comments:
  duoshuo:
    name: senzhang
    rcomments:
        num: 8
        avatar: 0
        time: 0
        title: 0
        admin: 1
        length: 20
  disqus:
    # In my architecture, duoshuo has higher priority then disqus,
    # because duoshuo is quicker then disqus in China.
    # if not only use in China, disqus is better.
    # disqus.name will be actived if duoshuo's name is null(Just delete it).
    name: senzhang
    rcomments:
        # Number of comments to show
        num: 8
        # Hide moderators' comments (1 for hidden, 0 for disabled)
        hide_mods: 0
        # Hide display images (1 for hidden, 0 for shown)
        hide_avatars: 1
        # Avatar size in pixels (32 by default)
        avatar_size: 32
        # Character-length of the excerpt (1000 by default)
        excerpt_length: 20
analytics:
    cnzz:
        uid: 1254858699

# Outputting
permalink: /:categories/:title
paginate_path: /page:num
paginate: 15
timezone: Asia/Shanghai

# Handling Reading
safe:         false
include:      []
exclude:      [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
keep_files:   []
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
plugins:   [jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Backwards-compatibility
relative_permalinks: false
